on: [push, pull_request]
name: Build and Test
permissions:
  contents: read
jobs:
  build-and-test:
    strategy:
      matrix:
        go-version: ["1.22", "1.x"]
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 1
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          go build ./...
      - name: Test
        run: |
          go test -v ./...
